//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public string IdReserva { get; set; }
        public string RutCliente { get; set; }
        public string FechaIngreso { get; set; }
        public string FechaSalida { get; set; }
        public string TipoHabitacion { get; set; }
        public int CantHuespedes { get; set; }
    }
}
