//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temporada
    {
        public int Temporada1 { get; set; }
        public string FechaInicio { get; set; }
        public string FechaTermino { get; set; }
        public string Tipo { get; set; }
    }
}
